### ISSUE TITLE
Production server can't find templates

### ISSUE THREAD

**Issue by jasford** [dziegler/django-css#10]
I have django-css working great on my dev environment (OS X) but when I try to run it on Ubuntu (Slicehost) with wsgi I get a pre-Django 500 server error:

```
[Wed Dec 30 15:57:12 2009] [error] [client 70.114.139.91] TemplateDoesNotExist: compressor/css.html
```

Django-css works great if I have COMPRESS = False. It successfully converts my .sass files to .css. The problem only occurs when I set COMPRESS = True.

What am I doing wrong?

**Comment by jasford** [comment]
this issue may have been solved with current version on GitHub. I had previously installed with easy_install. After removing that egg, cloning this repository, and then doing python setup.py install, I was able to get it working.

**Comment by dziegler** [comment]
thanks for letting me know, i'll update the version on pypi

**Comment by lmcnearney** [comment]
As of 1/17/2010, the easy_install method still doesn't work. I had to run setup.py install manually to get things working. Same TemplateDoesNotExist error on Ubuntu with wsgi. Works fine on Windows dev environment.

**Comment by dziegler** [comment]
Ok, this is finally fixed, sorry about that. It seems that zip_safe wasn't set to False in setup.py
